{% set name = "nipreps-versions" %}
{% set version = "1.0.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/nipreps_versions-{{ version }}.tar.gz
  sha256: 841ff517f320c07193487cf97b90768f1048aef18fac1298b597d9b4972feebf

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.8
    - flit-scm
    - pip
  run:
    - python >=3.8
    - setuptools-scm >=7
    - packaging

test:
  imports:
    - nipreps_versions
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/nipreps/version-schemes
  summary: Version schemes for nipreps tools
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - synchon
